# Apache License, Version 2.0

# these must be all lower case for comparisons

# correct spelling but ignore
dict_custom = {
    "adjoint", "adjugate",
    "allocator",
    "atomicity",
    "boolean",
    "decrement",
    "decrementing",
    "desaturate",
    "enqueue",
    "equiangular",
    "instantiation",
    "iterable",
    "merchantability",
    "natively",
    "parallelization",
    "parallelized",
    "precalculate",
    "prepend",
    "probabilistically",
    "recurse",
    "subclass", "subclasses", "subclassing",
    "subdirectory",
    "unregister",
    "unselected",
    "variadic",

    # accepted abbreviations
    "autocomplete",
    "config",
    "coord", "coords",
    "keyframe", "keyframing",
    "lookup", "lookups",
    "multi",
    "multithreading",
    "tooltip",

    # general computer terms
    "app",
    "autorepeat",
    "boids",
    "booleans",
    "codepage",
    "contructor",
    "decimator",
    "diff",
    "diffs",
    "endian",
    "env",
    "euler", "eulers",
    "hashable",
    "http",
    "jitter", "jittering",
    "keymap",
    "lerp",
    "metadata",
    "opengl",
    "preprocessor",
    "quantized",
    "searchable",
    "segfault",
    "stdin",
    "stdin",
    "stdout",
    "sudo",
    "touchpad", "touchpads",
    "trackpad", "trackpads",
    "unicode",
    "url",
    "vert", "verts",
    "voxel", "voxels",
    "wiki",

    # specific computer terms/brands
    "ffmpeg",
    "unix",
    "xinerama",

    # general computer graphics terms
    "atomics",
    "barycentric",
    "bezier",
    "bicubic",
    "centroid",
    "colinear",
    "compositing",
    "coplanar",
    "deinterlace",
    "emissive",
    "fresnel",
    "kerning",
    "lacunarity",
    "musgrave",
    "ngon", "ngons",
    "normals",
    "nurbs",
    "quaternions",
    "radiosity",
    "reflectance",
    "shader",
    "shaders",
    "specular",

    # blender terms
    "animsys",
    "animviz",
    "bge",
    "bmain",
    "bmesh",
    "bpy",
    "depsgraph",
    "doctree",
    "editmode",
    "eekadoodle",
    "fcurve",
    "mathutils",

    # should have apostrophe but ignore for now
    # unless we want to get really picky!
    "indices",
    "vertices",
}

# incorrect spelling but ignore anyway
dict_ignore = {
    "tri",
    "quad",
    "eg",
    "ui",
    "uv",
    "arg", "args",
    "vec",
    "loc",
    "dof",
    "bool",
    "dupli",
    "readonly",
    "filepath",
    "filepaths",
    "filename", "filenames",
    "submodule", "submodules",
    "dirpath",
    "x-axis",
    "y-axis",
    "z-axis",
    "a-z",
    "node-trees",

    # acronyms
    "cpu",
    "gpu",
    "rgb",
    "gpl",
    "nla",
    "api",
    "rhs",
    "lhs",
    "ik",
    "smpte",
    "gl",
}
